[package]
name = "skabelon"
version = "0.1.1"
edition = "2024"
description = "Simple templating engine for rust using angular syntax"
license = "GPL-3.0"

[dependencies]
serde = "1"
serde_json = "1"
glob = "0.3"

[dev-dependencies]
tempfile = "3"
